server:
  port: 8888

#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/practiceconfig


management:
  endpoints:
    web:
      exposure:
        include: refresh
spring:
  application:
    name: practiceconfig
  cloud:
    config:
      server:
        git:
          basedir: D:/test/config
          uri: https://github.com/jamesnono/SpringCloudConfig
          search-paths: config-repo

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/jamesnono/SpringCloudConfig/config-repo
#          repos:
#            simple: https://github.com/jamesnono/SpringCloudConfig
#            local:
#              pattern: local*
#              uri: classpath:/practiceconfig
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/


